spring.application.name=wemeet
spring.thymeleaf.cache=false
spring.datasource.url=${DB_URL:jdbc:h2:file:./build/wemeetdb;MODE=MariaDB;DATABASE_TO_LOWER=TRUE}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
